default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :ci_unittests do
    run_tests(
      app_name: "Rijksmuseum",
      device: "iPhone 14",
      project: "Rijksmuseum.xcodeproj",
      scheme: "Rijksmuseum",
      reinstall_app: true,
      app_identifier: "com.iandundas.Rijksmuseum",
      xcargs: "-skipPackagePluginValidation"
    )
  end
end